FORMAT: 1A

# Awesome

Master节点接口设计。

# Data Structure

## `HostInfo` (object)

+ id: 1 (string) - 主机ID
+ ip_inner: 1.1.1.1 (string) - 主机内网IP
+ ip_out: 2.2.2.2 (string) - 主机外网IP
+ hostname: 数据检索 (string) - 主机名
+ env: online (string) - 主机所属环境
+ owner: 数据检索组 (string) - 主机所属者
+ dominname: 测试服务器 (string) - 主机的名字
+ comment: My NO.1 Owesome Server (string) - 主机的备注

## `Response` (object)

+ message: Success (string) - 服务器相应结果信息
+ error: 0 (string) - 服务器返回错误信息
+ data (array[HostInfo]) - 服务器返回数据

# Group Hosts

## Hosts Monitor [/hostmanager]

### List All Hosts [GET]

获取所有主机列表。

+ Response 200 (application/json)

+ Attributes (Response)

### Create a Host Record [POST]

注册一个新主机到监控列表里。

+ Request (application/json)
    
    + Attributes (HostInfo)

+ Response 200 (application/json)
    
    + Attributes (Response)
    

## Host Handler [/hostmanager/{host_id}]

### Update a Host Record [PUT]

修改一个主机信息

+ Request (application/json)

    + Parameters
        + host_id (number) 
        
            ID of the host in the form of an integer
    
    + Attributes (HostInfo)

+ Response 200 (application/json)

    + Attributes (Response)
        
        
### Remove a Host Record [DELETE]

+ Request (application/json)
    
    + Parameters
        + host_id (number)
            
            ID of the Question in the form of an integer)
    
    

+ Response 200 (application/json)
    
    + Attributes (Response)